CREATE DATABASE IF NOT EXISTS my_database;
USE my_database;

-- Crear la tabla USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMB_USUARIO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(40) NOT NULL,
    CONTRASEÑA VARCHAR(20) NOT NULL
);

-- Crear la tabla PROFESORES
CREATE TABLE PROFESORES (
    ID_PROFE INT AUTO_INCREMENT PRIMARY KEY,
    NOMB_PROFE VARCHAR(20) NOT NULL
);

-- Crear la tabla COMENTARIOS
CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_PROFE INT,
    COMENTARIO VARCHAR(200),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PROFE) REFERENCES PROFESORES(ID_PROFE)
);

-- Crear la tabla DOCUMENTOS
CREATE TABLE DOCUMENTOS (
    ID_DOCUMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROF INT,
    ID_ESTUDIANTE INT,
    FECHA_EXAMEN DATE,
    RUTA_ARCHIVO VARCHAR(255),
    DESCRIPCION VARCHAR(300),
    FOREIGN KEY (ID_PROF) REFERENCES PROFESORES(ID_PROFE),
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIOS(ID_USUARIO)
);
INSERT INTO USUARIOS (NOMB_USUARIO, CORREO, CONTRASEÑA) VALUES
('usuario1', 'usuario1@example.com', 'password1'),
('usuario2', 'usuario2@example.com', 'password2');

INSERT INTO PROFESORES (NOMB_PROFE) VALUES
('profe1'),
('profe2');

INSERT INTO COMENTARIOS (ID_USUARIO, ID_PROFE, COMENTARIO) VALUES
(1, 1, 'Comentario del usuario1 al profe1'),
(2, 2, 'Comentario del usuario2 al profe2');

INSERT INTO DOCUMENTOS (ID_PROF, ID_ESTUDIANTE, FECHA_EXAMEN, RUTA_ARCHIVO, DESCRIPCION) VALUES
(1, 1, '2024-05-19', '/ruta/archivo1', 'Descripcion del documento 1'),
(2, 2, '2024-06-19', '/ruta/archivo2', 'Descripcion del documento 2');
USE my_database;
select * from DOCUMENTOS;